<?php
/**
 * @file
 * Niquesa Signup module
 *
 */


/**
 * Implement hook_permission().
 */
function niquesa_signup_permission() {
    return array(
        'administer niquesa signup' => array(
            'title' => 'Administer Niquesa Signup',
            'description' => 'Change settings of Niquesa Signup module',
        ),
    );
}


/**
 * Implement hook_menu().
 */
function niquesa_signup_menu() {
    return array(
        'admin/config/niquesa/signup' => array(
            'title' => 'Niquesa Signup',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('niquesa_signup_admin_form'),
            'access arguments' => array('administer niquesa signup'),
        ),
    );
}


/**
 * Definition of admin form
 */
function niquesa_signup_admin_form() {
    return system_settings_form(array(
        'niquesa_signup_mailchimp_url' => array(
            '#type' => 'textfield',
            '#title' => 'Mailchimp URL',
            '#default_value' => variable_get('niquesa_signup_mailchimp_url', ''),
            '#required' => true,
        ),
    ));
}


/**
 * Implement hook_theme_registry_alter().
 */
function niquesa_signup_theme_registry_alter(&$theme_registry) {
	if (isset($theme_registry['form_element']))
		$theme_registry['form_element']['function'] = "theme_niquesa_signup_form_element";
}

/**

 * An implementation of form_element theme hook.
 * It's mostly a 1:1 copy of theme_form_element, with an additional condition for displaying a wrapper div.
 * It skips the wrapper if a '#skip_wrapper' key is set (to true) in element array.
 */
function theme_niquesa_signup_form_element($variables) {
	$element = &$variables['element'];

	// This function is invoked as theme wrapper, but the rendered form element
	// may not necessarily have been processed by form_builder().
	$element += array(
		'#title_display' => 'before',
	);

	// Add element #id for #type 'item'.
	if (isset($element['#markup']) && !empty($element['#id'])) {
		$attributes['id'] = $element['#id'];
	}
	// Add element's #type and #name as class to aid with JS/CSS selectors.
	$attributes['class'] = array('form-item');
	if (!empty($element['#type'])) {
		$attributes['class'][] = 'form-type-' . strtr($element['#type'], '_', '-');
	}
	if (!empty($element['#name'])) {
		$attributes['class'][] = 'form-item-' . strtr($element['#name'], array(' ' => '-', '_' => '-', '[' => '-', ']' => ''));
	}
	// Add a class for disabled elements to facilitate cross-browser styling.
	if (!empty($element['#attributes']['disabled'])) {
		$attributes['class'][] = 'form-disabled';
	}

	$output = "";

	if (isset($variables['element']['#name']) && !isset($variables['element']['#skip_wrapper']))
		$output = '<div' . drupal_attributes($attributes) . '>' . "\n";

	// If #title is not set, we don't display any label or required marker.
	if (!isset($element['#title'])) {
		$element['#title_display'] = 'none';
	}
	$prefix = isset($element['#field_prefix']) ? '<span class="field-prefix">' . $element['#field_prefix'] . '</span> ' : '';
	$suffix = isset($element['#field_suffix']) ? ' <span class="field-suffix">' . $element['#field_suffix'] . '</span>' : '';

	switch ($element['#title_display']) {
		case 'before':
		case 'invisible':
			$output .= ' ' . theme('form_element_label', $variables);
			$output .= ' ' . $prefix . $element['#children'] . $suffix . "\n";
			break;

		case 'after':
			$output .= ' ' . $prefix . $element['#children'] . $suffix;
			$output .= ' ' . theme('form_element_label', $variables) . "\n";
			break;

		case 'none':
		case 'attribute':
			// Output no label and no required marker, only the children.
			$output .= ' ' . $prefix . $element['#children'] . $suffix . "\n";
			break;
	}

	if (!empty($element['#description'])) {
		$output .= '<div class="description">' . $element['#description'] . "</div>\n";
	}

	if (isset($variables['element']['#name']) && !isset($variables['element']['#skip_wrapper']))
		$output .= "</div>\n";

	return $output;
}


/**
 * Signup form definition.
 */
function niquesa_signup_signup_form ($form, &$form_state){
	if (isset($form_state['values']))
		$values = $form_state['values'];

    //'//niquesahotels.us8.list-manage.com/subscribe/post?u=205a50f031244255c8e7de553&id=2bb1bcb50e';
    $form['#action'] = variable_get('niquesa_signup_mailchimp_url', '');
    $form['#method'] = 'post';
    $form['#attributes'] = array(
        'target' => '_blank',
    );

	$form['FNAME'] = array(
		'#type' => 'textfield',
		'#default_value' => isset($values['FNAME']) ? $values['FNAME'] : '',
		'#attributes' => array(
			'placeholder' => 'FIRST NAME',
			'class' => array('text-box'),
		),
		'#size' => 35,
		'#skip_wrapper' => true,
	);

	$form['LNAME'] = array(
		'#type' => 'textfield',
		'#default_value' => isset($values['LNAME']) ? $values['LNAME'] : '',
		'#attributes' => array(
			'placeholder' => 'LAST NAME',
			'class' => array('text-box'),
		),
		'#size' => 35,
		'#skip_wrapper' => true,
	);

	$form['EMAIL'] = array(
		'#type' => 'textfield',
		'#default_value' => isset($values['EMAIL']) ? $values['EMAIL'] : '',
		'#attributes' => array(
			'placeholder' => 'EMAIL ADDRESS',
			'class' => array('text-box'),
		),
		'#size' => 35,
		'#skip_wrapper' => true,
	);

    $form['EMAILTYPE'] = array(
        '#type' => 'hidden',
        '#value' => 'html',
    );

	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Sign Up'),
		# '#ajax' => array (
		# 	'callback' => 'niquesa_signup_signup_form_callback',
		# 	'wrapper' => 'niquesa-signup-signup-form',
		# 	'effect' => 'fade',
		# ),
		'#attributes' => array(
			'class' => array('a-button', 'purple', 'decorated'),
		),
	);

	$form['submit_uri'] = array(
		'#type' => 'hidden',
		'#value' => token_replace('[current-page:url]'),
	);

	honeypot_add_form_protection($form, $form_state, array('honeypot', 'time_restriction'));

	return $form;
}


/**
 * Implement hook_block_info().
 */
function niquesa_signup_block_info() {
	return array(
		'niquesa_signup' => array (
			'info' => t('Niquesa Signup Form'),
		),
	);
}


/**
 * Implement hook_block_view().
 */
function niquesa_signup_block_view($delta='') {
	$block = array();

	switch($delta) {
		case 'niquesa_signup':
			$block['subject'] = null;
			$block['content'] = drupal_get_form('niquesa_signup_signup_form');
			break;
	}

	return $block;
}


/**
 * Implement hook_entity_info().
 */
function niquesa_signup_entity_info() {
	return array(
		'niquesa_signup_user' => array(
			'label' => 'Niquesa Signup User',
			'controller class' => 'EntityAPIController',
			'views controller class' => 'EntityDefaultViewsController',
			'base table' => 'niquesa_signup_user',
			'entity keys' => array(
				'id' => 'uid',
				'label' => 'name',
			),
		),
	);
}
